
/* ================================================================ *
 *          Automatically generated by n-Blocks Studio 2.0          *
 *                                                                  *
 *                         www.n-blocks.net                         *
 * ================================================================ */
#include "nlib\nblocks.h"
#include "nlib\BSP\bsp.h"
// Custom nodes:
#include "nlib\Ticker\ticker.h"
#include "nlib\L298\L298.h"
#include "nlib\FlipFlop\flipflop.h"
#include "nlib\GPOUT\gpout.h"
#include "nlib\Counter\counter.h"

// -*-*- List of node objects -*-*-
nBlock_Ticker        nb_nBlockNode0_Ticker   (1000);
nBlock_L298          nb_nBlockNode1_L298     (LED2, LED3, LED4);
nBlock_Ticker        nb_nBlockNode2_Ticker   (100);
nBlock_FlipFlop      nb_nBlockNode3_FlipFlop (0);
nBlock_GPOUT         nb_nBlockNode4_GPOUT    (LED1, PullNone, 1);
nBlock_Counter       nb_nBlockNode5_Counter  (4);

// -*-*- List of connection objects -*-*-
nBlockConnection    n_conn0( &nb_nBlockNode3_FlipFlop, 0,    &nb_nBlockNode4_GPOUT,    0);
nBlockConnection    n_conn1( &nb_nBlockNode2_Ticker,   0,    &nb_nBlockNode3_FlipFlop, 0);
nBlockConnection    n_conn2( &nb_nBlockNode5_Counter,  0,    &nb_nBlockNode1_L298,     0);
nBlockConnection    n_conn3( &nb_nBlockNode0_Ticker,   0,    &nb_nBlockNode5_Counter,  0);


// -*-*- Main function -*-*-
int main(void) {
    SetupWorkbench();
    while(1) {
        ProgressNodes();
        
        // Your custom code here!
    }
}
